import type { TitleCandidate } from "./types";

export const initialTitleCandidates: TitleCandidate[] = [
  {
    id: "title-001",
    title: "Mapeo de puestos críticos: cómo proteger la continuidad de tu empresa",
    client: "Adecco Perú",
    campaign: "Agosto 2026",
    objective: "Explicar cómo priorizar posiciones cuya ausencia compromete la operación.",
    audience: "Gerencias de Recursos Humanos y líderes de operaciones",
    intent: "Resolver",
    focus: "Método práctico de identificación y priorización",
    opportunity: "Conectar continuidad operativa con planificación del talento.",
    risk: "Evitar presentar criterios internos como una norma universal.",
    status: "evaluating",
    score: 91,
    owner: "Alexander",
    updatedAt: "Hoy, 11:42",
    tags: ["talento", "continuidad", "planificación"],
    duplicate: {
      score: 28,
      level: "low",
      relatedTitle: "Planificación de talento para posiciones estratégicas",
      relatedDate: "Marzo 2026",
      recommendation: "Crear",
      resolved: true,
    },
    agents: [
      { agent: "Estratega SEO", verdict: "favorable", score: 93, summary: "La intención es clara y el título responde a un problema operativo concreto.", findings: ["Tema diferenciable", "Verbo de utilidad presente"] },
      { agent: "Editor de marca", verdict: "favorable", score: 90, summary: "Lenguaje profesional, directo y consistente con una audiencia ejecutiva.", findings: ["Tono consultivo", "Promesa comprensible"] },
      { agent: "Detector de duplicidad", verdict: "favorable", score: 88, summary: "Existe proximidad temática, pero el enfoque de continuidad es suficientemente distinto.", findings: ["28% de similitud", "Intención distinta"] },
      { agent: "Juez", verdict: "favorable", score: 91, summary: "Puede avanzar a decisión humana; no se detectan bloqueos críticos.", findings: ["Evidencia resumida", "Aprobación humana requerida"] },
    ],
    history: [
      { id: "h-1", action: "Evaluación completada", actor: "Orquestador", at: "Hoy, 11:42", detail: "Cuatro especialidades ejecutadas en una ronda." },
      { id: "h-2", action: "Título propuesto", actor: "Alexander", at: "Hoy, 11:38", detail: "Creado para la campaña de agosto." },
    ],
  },
  {
    id: "title-002",
    title: "¿Cómo reducir la rotación laboral sin afectar la productividad?",
    client: "Adecco Perú",
    campaign: "Agosto 2026",
    objective: "Orientar a empresas que necesitan reducir salidas recurrentes.",
    audience: "Responsables de RR. HH. en empresas medianas",
    intent: "Resolver",
    focus: "Acciones de diagnóstico y retención sostenibles",
    opportunity: "Alto interés recurrente en gestión de personas.",
    risk: "No prometer resultados sin contexto sectorial.",
    status: "changes_requested",
    score: 78,
    owner: "Mauricio",
    updatedAt: "Hoy, 10:18",
    tags: ["rotación", "retención", "productividad"],
    duplicate: {
      score: 86,
      level: "high",
      relatedTitle: "Estrategias para reducir la rotación de personal",
      relatedDate: "Enero 2026",
      recommendation: "Actualizar",
      resolved: false,
    },
    agents: [
      { agent: "Estratega SEO", verdict: "attention", score: 80, summary: "La intención es útil, pero el enfoque compite con una nota existente.", findings: ["Consulta relevante", "Canibalización posible"] },
      { agent: "Editor de marca", verdict: "favorable", score: 88, summary: "El lenguaje es natural y evita afirmaciones absolutas.", findings: ["Buena pregunta", "Promesa prudente"] },
      { agent: "Detector de duplicidad", verdict: "blocked", score: 55, summary: "La similitud semántica exige decidir si se actualiza o se descarta.", findings: ["86% de similitud", "Misma intención"] },
      { agent: "Juez", verdict: "blocked", score: 62, summary: "No debe aprobarse hasta resolver la duplicidad con intervención humana.", findings: ["Bloqueo activo", "Requiere decisión"] },
    ],
    history: [
      { id: "h-3", action: "Cambios solicitados", actor: "Angie", at: "Hoy, 10:18", detail: "Definir si la nota de enero se actualizará." },
      { id: "h-4", action: "Duplicidad detectada", actor: "Detector de duplicidad", at: "Hoy, 10:04", detail: "Similitud semántica del 86%." },
    ],
  },
  {
    id: "title-003",
    title: "Evaluación por competencias: claves para tomar mejores decisiones de contratación",
    client: "Adecco Perú",
    campaign: "Agosto 2026",
    objective: "Mostrar el valor de evaluar capacidades observables durante la selección.",
    audience: "Equipos de selección y líderes de área",
    intent: "Informar",
    focus: "Criterios prácticos y errores frecuentes",
    opportunity: "Fortalecer el posicionamiento consultivo de selección.",
    risk: "Diferenciar recomendaciones de requisitos normativos.",
    status: "approved",
    score: 94,
    owner: "Angie",
    updatedAt: "Ayer, 17:25",
    tags: ["selección", "competencias", "contratación"],
    duplicate: {
      score: 19,
      level: "low",
      relatedTitle: "Cómo mejorar tus procesos de selección",
      relatedDate: "Noviembre 2025",
      recommendation: "Crear",
      resolved: true,
    },
    agents: [
      { agent: "Estratega SEO", verdict: "favorable", score: 95, summary: "Tema específico con intención informativa y aplicación clara.", findings: ["Entidad principal visible", "Buen nivel de detalle"] },
      { agent: "Editor de marca", verdict: "favorable", score: 94, summary: "El título combina claridad y autoridad sin exagerar.", findings: ["Tono consultivo", "Audiencia clara"] },
      { agent: "Detector de duplicidad", verdict: "favorable", score: 96, summary: "No se observa solapamiento relevante con el historial.", findings: ["19% de similitud", "Enfoque nuevo"] },
      { agent: "Juez", verdict: "favorable", score: 94, summary: "Título aprobado por Angie y listo para iniciar una nota.", findings: ["Sin bloqueos", "Decisión registrada"] },
    ],
    history: [
      { id: "h-5", action: "Título aprobado", actor: "Angie", at: "Ayer, 17:25", detail: "Aprobación humana registrada." },
      { id: "h-6", action: "Evaluación completada", actor: "Orquestador", at: "Ayer, 17:11", detail: "Sin bloqueos críticos." },
    ],
  },
  {
    id: "title-004",
    title: "Outsourcing de planillas: señales de que tu empresa necesita apoyo especializado",
    client: "Adecco Perú",
    campaign: "Septiembre 2026",
    objective: "Ayudar a reconocer problemas operativos que justifican evaluar un servicio especializado.",
    audience: "Gerencias administrativas y financieras",
    intent: "Contratar",
    focus: "Señales operativas y criterios de evaluación",
    opportunity: "Vincular una necesidad concreta con una solución de Adecco.",
    risk: "Mantener el CTA coherente y no convertir el contenido en publicidad directa.",
    status: "proposed",
    score: 87,
    owner: "Alexander",
    updatedAt: "Ayer, 15:40",
    tags: ["outsourcing", "planillas", "operaciones"],
    duplicate: {
      score: 34,
      level: "low",
      relatedTitle: "Beneficios de tercerizar procesos administrativos",
      relatedDate: "Abril 2026",
      recommendation: "Crear",
      resolved: true,
    },
    agents: [
      { agent: "Estratega SEO", verdict: "favorable", score: 89, summary: "La intención comercial se sostiene en una necesidad informativa.", findings: ["Problema visible", "Conversión contextual"] },
      { agent: "Editor de marca", verdict: "attention", score: 82, summary: "Conviene revisar que el cuerpo futuro mantenga un tono educativo.", findings: ["Evitar venta excesiva", "CTA final"] },
      { agent: "Detector de duplicidad", verdict: "favorable", score: 91, summary: "El servicio es similar, pero el ángulo de señales operativas es nuevo.", findings: ["34% de similitud", "Ángulo diferenciador"] },
      { agent: "Juez", verdict: "favorable", score: 87, summary: "Puede pasar a revisión humana con una advertencia editorial menor.", findings: ["Sin bloqueos", "Revisar tono"] },
    ],
    history: [
      { id: "h-7", action: "Título propuesto", actor: "Alexander", at: "Ayer, 15:40", detail: "Campaña de septiembre." },
    ],
  },
  {
    id: "title-005",
    title: "Tendencias de empleo en Perú que marcarán el cierre de 2026",
    client: "Adecco Perú",
    campaign: "Septiembre 2026",
    objective: "Analizar cambios relevantes del mercado laboral peruano.",
    audience: "Líderes empresariales y profesionales",
    intent: "Informar",
    focus: "Tendencias respaldadas por datos y fuentes vigentes",
    opportunity: "Contenido de actualidad con potencial de menciones.",
    risk: "Todos los datos deberán confirmar fuente, fecha y alcance antes de redactar.",
    status: "rejected",
    score: 71,
    owner: "Mauricio",
    updatedAt: "12 ago., 16:30",
    tags: ["empleo", "Perú", "tendencias"],
    duplicate: {
      score: 41,
      level: "medium",
      relatedTitle: "Perspectivas del mercado laboral peruano 2026",
      relatedDate: "Febrero 2026",
      recommendation: "Complementar",
      resolved: true,
    },
    agents: [
      { agent: "Estratega SEO", verdict: "attention", score: 76, summary: "El tema depende de información reciente todavía no confirmada.", findings: ["Temporalidad alta", "Fuentes pendientes"] },
      { agent: "Editor de marca", verdict: "favorable", score: 86, summary: "Título claro, aunque requiere precisión en el alcance temporal.", findings: ["Buen contexto país", "Fecha visible"] },
      { agent: "Detector de duplicidad", verdict: "attention", score: 78, summary: "Puede complementar una pieza anterior si aporta datos nuevos.", findings: ["41% de similitud", "Actualizar contexto"] },
      { agent: "Juez", verdict: "attention", score: 71, summary: "Fue rechazado por falta de evidencia actual suficiente.", findings: ["Decisión humana", "Puede retomarse"] },
    ],
    history: [
      { id: "h-8", action: "Título rechazado", actor: "Mauricio", at: "12 ago., 16:30", detail: "No existen aún datos autorizados para sostener el enfoque." },
    ],
  },
];
